### ISSUE TITLE
What data do you use to train the model?

### ISSUE THREAD

**Issue by dectrfov** [CVN-OPIS/MotorNN#11]
Hello,
This work is very interesting and I think this is very useful in my research task.
I want to reproduce the experiments described in the paper firstly.
Thus, I wonder what data are used to implement the experiments.
I CANNOT find gen_sim_pkls.py to generate the simulated data.
Furthermore, I also download the dataset but I don't know what are corresponding train and test data.
Thanks for your reply.
Best regards,
Hao-Hsiang Yang

**Comment by sagarverma** [comment]
Hi @dectrfov 

Thanks for showing interest in our work. This repository has changed a lot since AAAI2020 acceptance. I will make a release of our AAAI2020 code, data, and weights. I will do this within three days.

**Comment by dectrfov** [comment]
Very thanks for your reply.
I look forward to seeing new codes and experimental setting.

**Comment by sagarverma** [comment]
I have created a AAAI2020_release branch. It will take me 2 more days to upload data and weights.

**Comment by dectrfov** [comment]
Very thanks for your reply. I have seen the new branch with experimental codes. Will you upload the data setting and model weights?

**Comment by sagarverma** [comment]
Yes, I will upload the dataset and model weights.

**Comment by sagarverma** [comment]
I have refactored the code. All tests are passing and I am able to train. I have also attached right version of data in the relase. I am training couple of models for release. I will attach them asap. Let me know if you face any problem.
