### ISSUE TITLE
Issue of multiple outputs and mae metrics

### ISSUE THREAD

**Issue by dectrfov** [CVN-OPIS/MotorNN#14]
Thanks for updating and I also run the codes but I find some bug during model training.
First, in your paper, the outputs are voltage_d, voltage_q, and speed, but your demonstration command only contains 'current_d'. 
Second, after running the code and I find some metrics in log are confusing. 
I think mae, rmse should be >= 0 ?
![image](https://user-images.githubusercontent.com/22385088/94343523-598ea580-004b-11eb-8bc9-dcea7370fce5.png)

Thanks for your reply.
Best regards,
Hao-Hsiang Yang

**Comment by sagarverma** [comment]
You are welcome. Thanks for reporting this bug.

In the paper, the predicted signals are 'current_d,current_q,torque', you can also predict 'voltage_d,voltage_q,speed' from them,  any combination is possible. Code should also allow to given any number of input and output as long as it is passed in the args. Let me know if you face any problem with a particular input-output combination.

Yes, these reported metrics are wrong. I will check and correct them asap.

**Comment by dectrfov** [comment]
Very thanks for your reply.

But I find when output is  'current_d', the parameters of models are consistent with paper described.
When I change the outputs as 'voltage_d,voltage_q,speed',  the parameters are increased and not consistent with paper described.
Therefore, I think the predicted signal in the paper is only single output.
Additionally, I find the error are 'denormalized', which may make the final errors are not >= 0

Best regards,
Hao-Hsiang Yang

**Comment by sagarverma** [comment]
You are welcome.

The parameters described int the model are for single output. We train three different models. I can understand that it is confusing from the architecture diagram and the fact that we have not mentioned this explicitly. I will add parameters of both three channel and single channel model.
Yes, the metrics are first computed on outputs which are in normalised range and then the aggregated metrics are denormalised. This is can be resolved by taking abs or just using normalised metrics. We preferred to report in current way to make it consistent with the quantities natural range.

Best regards,
Sagar VERMA

**Comment by dectrfov** [comment]
Very thanks for your reply.
I also perform the experiments for 3 outputs and the errors (SMAPE) are larger than the paper described.
I think it makes sense.

Best regards,
Hao-Hsiang Yang

**Comment by sagarverma** [comment]
Added a note in the readme for now. I will change metrics later.
