### ISSUE TITLE
Understanding downloadable motor dataset 

### ISSUE THREAD

**Issue by Hritikbansal** [CVN-OPIS/MotorNN#15]
Hi,

Congratulations for your AAAI 2020 paper, and the work seems really interesting. I was working on a project where we might want to evaluate our models on your dataset. I have a few questions from the Motor Data which you have provided.

1. What do you mean by 'LM10.mat', 'LM68.mat', 'NoLM.mat'? Essentially, how do different .mat files differ? Some of these files have 12k datapoints, and some of them have ~50k datapoints. Why is that?

2. In your paper, you have mentioned that 'Data from 10 various operating conditions are collected.' 
    a) I understand that each variation means you have different speed and load but can you pinpoint where do those variations exist in the dataset, and how can we separate them?
    b) What are the values of rotor speed and load torques for each of the operating conditions? 

Thanks!

**Comment by sagarverma** [comment]
Thanks for taking interest in our paper. 

1. LM in 'LM*.mat' means Load Machine. XX in 'LMXX.mat' means motor has a constant speed of XX Hz, and torque load varies from 0 to 120% of nominal torque(25Nm). In case of speed variations mat files speed varies when motor is at constant torque load. Number of data points depends on experiment duration and acquisition rate. 

2. Variations are
   
- Constant zero torque, speed varies
- Constant nominal torque, speed varies
- Constant speed, torque varies
- Constant zero torque, oscillations in speed
- Constant nominal torque, oscillations in speed
- Torque step at constant speed
- Torque ramp at constant speed
- Speed ramp at constant nominal torque
- Speed ramp at constant zero torque
- Speed and Torque both vary

Files cannot be divided according to operating conditions, multiple operating conditions present in one file. It is easier to generate one unique type of operating condition using Simulink model provided [here](https://github.com/INRIA-OPIS/MotorRefGen). We will shortly release a more electrical engineering oriented benchmarking dataset proposed in this [paper](https://sagarverma.github.io/others/IECON_MotorBenchmarking.pdf).

**Comment by Hritikbansal** [comment]
Hi Sagar!

Thanks for your reply! 
I see, so what I am able to understand is that the motor data does not contain reference speed and torque signals which decide the operating conditions. Am I right? It would have great if those are also provided along with it.
Thanks for pointing me out to the relevant links!
All the best for the next release of new dataset.

**Comment by sagarverma** [comment]
Hi Hritik

You are welcome. I have reference speed and reference load for some of the experiments. They are available [here](https://drive.google.com/drive/folders/1EDpf8YANhc7RQwFumV-c0et8u_McJE5k?usp=sharing).

Thanks!

**Comment by Hritikbansal** [comment]
Thanks Sagar for sharing the appropriate data. It will definitely help!
