### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wen-coder** [CVN-OPIS/MotorNN#18]
Hello

I recently read your interesting paper and I would like to replicate your project.
But I can't download your dataset, is there something wrong with your dataset, can you post a link to the latest dataset

**Comment by sagarverma** [comment]
Please find the dataset here [https://drive.google.com/file/d/1G72jw_VQ19YziD71QedSV2ofeUIGkUMz/view?usp=sharing](https://drive.google.com/file/d/1G72jw_VQ19YziD71QedSV2ofeUIGkUMz/view?usp=sharing)
